import Foundation

// Таблицы калибровки — пока пустые, заполним позже.
// Формат: [trim_m: [level_cm: volume_m3]]

let data_No_3_P_S: CalibrationTable = [:]
let data_No_3_P_U: CalibrationTable = [:]
let data_No_4_P_S: CalibrationTable = [:]
let data_No_4_P_U: CalibrationTable = [:]
let data_No_4_S_S: CalibrationTable = [:]
let data_No_4_S_U: CalibrationTable = [:]
let data_No_5_P_S: CalibrationTable = [:]
let data_No_5_P_U: CalibrationTable = [:]
let data_No_5_S_S: CalibrationTable = [:]
let data_No_5_S_U: CalibrationTable = [:]
let data_5_S: CalibrationTable = [:]
let data_5_U: CalibrationTable = [:]
let data_4_S: CalibrationTable = [:]
let data_4_U: CalibrationTable = [:]
let data_7_S: CalibrationTable = [:]
let data_7_U: CalibrationTable = [:]
let data_6_S: CalibrationTable = [:]
let data_6_U: CalibrationTable = [:]
let data_8:   CalibrationTable = [:]
let data_No_3_S_S: CalibrationTable = [:]
let data_No_3_S_U: CalibrationTable = [:]
let data_2:   CalibrationTable = [:]
let data_1:   CalibrationTable = [:]
let data_3:   CalibrationTable = [:]
